tag @s remove unique_axolotl
tag @s remove unique_bat
tag @s remove unique_bee
tag @s remove unique_cat
tag @s remove unique_chicken
tag @s remove unique_cow
tag @s remove unique_donkey
tag @s remove unique_fish
tag @s remove unique_fox
tag @s remove unique_glow_squid
tag @s remove unique_goat
tag @s remove unique_iron_golem
tag @s remove unique_hoglin
tag @s remove unique_horse
tag @s remove unique_llama
tag @s remove unique_mooshroom
tag @s remove unique_mule
tag @s remove unique_ocelot
tag @s remove unique_pig
tag @s remove unique_polar_bear
tag @s remove unique_pufferfish
tag @s remove unique_rabbit
tag @s remove unique_salmon
tag @s remove unique_sheep
tag @s remove unique_skeleton_horse
tag @s remove unique_squid
tag @s remove unique_strider
tag @s remove unique_tropicalfish
tag @s remove unique_turtle
tag @s remove unique_villager
tag @s remove unique_wandering_trader
tag @s remove unique_wolf
tag @s remove unique_zoglin

tag @s remove unique_blaze
tag @s remove unique_cave_spider
tag @s remove unique_creeper
tag @s remove unique_drowned
tag @s remove unique_elder_guardian
tag @s remove unique_enderman
tag @s remove unique_endermite
tag @s remove unique_evocation_illager
tag @s remove unique_ghast
tag @s remove unique_guardian
tag @s remove unique_husk
tag @s remove unique_magma_cube
tag @s remove unique_phantom
tag @s remove unique_piglin
tag @s remove unique_piglin_brute
tag @s remove unique_ravager
tag @s remove unique_shulker
tag @s remove unique_silverfish
tag @s remove unique_slime
tag @s remove unique_stray
tag @s remove unique_spider
tag @s remove unique_vex
tag @s remove unique_vindicator
tag @s remove unique_witch
tag @s remove unique_wither_skeleton
tag @s remove unique_wither
tag @s remove unique_zombie_pigman
tag @s remove unique_zombie_villager
tag @s remove unique_zombie
tag @s remove phantom