tag @s remove adv49
tag @s remove adv50
tag @s remove adv51
tag @s remove adv52
tag @s remove adv53
tag @s remove adv54
tag @s remove adv55
tag @s remove adv56
tag @s remove adv57
tag @s remove adv58
tag @s remove adv59
tag @s remove adv60
tag @s remove adv61
tag @s remove adv62
tag @s remove adv63
tag @s remove adv64
tag @s remove adv65
tag @s remove adv66
tag @s remove adv67
tag @s remove adv68
tag @s remove adv81
tag @s remove adv82
tag @s remove adv83
tag @s remove adv84
tag @s remove adv85

scoreboard players set @s uniqueAtk 0

tag @s remove biome_bamboo_jungle
tag @s remove biome_bamboo_jungle_hills
tag @s remove biome_beach
tag @s remove biome_birch_forest
tag @s remove biome_birch_forest_hills
tag @s remove biome_birch_forest_hills_mutated
tag @s remove biome_birch_forest_mutated
tag @s remove biome_cold_beach
tag @s remove biome_cold_ocean
tag @s remove biome_cold_taiga
tag @s remove biome_cold_taiga_hills
tag @s remove biome_cold_taiga_mutated
tag @s remove biome_deep_cold_ocean
tag @s remove biome_deep_frozen_ocean
tag @s remove biome_deep_lukewarm_ocean
tag @s remove biome_deep_ocean
tag @s remove biome_deep_warm_ocean
tag @s remove biome_desert
tag @s remove biome_desert_hills
tag @s remove biome_desert_mutated
tag @s remove biome_extreme_hills
tag @s remove biome_extreme_hills_edge
tag @s remove biome_extreme_hills_forest
tag @s remove biome_extreme_hills_mutated
tag @s remove biome_extreme_hills_mutated_forest
tag @s remove biome_flower_forest
tag @s remove biome_forest
tag @s remove biome_forest_hills
tag @s remove biome_frozen_ocean
tag @s remove biome_frozen_river
tag @s remove biome_ice_mountains
tag @s remove biome_ice_plains
tag @s remove biome_ice_plains_spikes
tag @s remove biome_jungle
tag @s remove biome_jungle_edge
tag @s remove biome_jungle_edge_mutated
tag @s remove biome_jungle_hills
tag @s remove biome_jungle_mutated
tag @s remove biome_lukewarm_ocean
tag @s remove biome_mega_spruce_taiga
tag @s remove biome_mega_spruce_taiga_hills
tag @s remove biome_mega_taiga
tag @s remove biome_mega_taiga_hills
tag @s remove biome_mesa
tag @s remove biome_mesa_bryce
tag @s remove biome_mesa_plateau
tag @s remove biome_mesa_plateau_mutated
tag @s remove biome_mesa_plateau_stone
tag @s remove biome_mesa_plateau_stone_mutated
tag @s remove biome_mushroom_island
tag @s remove biome_mushroom_island_shore
tag @s remove biome_ocean
tag @s remove biome_plains
tag @s remove biome_river
tag @s remove biome_roofed_forest
tag @s remove biome_roofed_forest_mutated
tag @s remove biome_savanna
tag @s remove biome_savanna_mutated
tag @s remove biome_savanna_plateau
tag @s remove biome_savanna_plateau_mutated
tag @s remove biome_stone_beach
tag @s remove biome_swamp
tag @s remove biome_swamp_mutated
tag @s remove biome_taiga
tag @s remove biome_taiga_hills
tag @s remove biome_taiga_mutated
tag @s remove biome_warm_ocean

tag @s remove killed_blaze
tag @s remove killed_cave_spider
tag @s remove killed_creeper
tag @s remove killed_drowned
tag @s remove killed_elder_guardian
tag @s remove killed_ender_dragon
tag @s remove killed_enderman
tag @s remove killed_endermite
tag @s remove killed_evocation_illager
tag @s remove killed_ghast
tag @s remove killed_guardian
tag @s remove killed_husk
tag @s remove killed_magma_cube
tag @s remove killed_phantom
tag @s remove killed_piglin
tag @s remove killed_piglin_brute
tag @s remove killed_pillager
tag @s remove killed_ravager
tag @s remove killed_shulker
tag @s remove killed_silverfish
tag @s remove killed_skeleton
tag @s remove killed_slime
tag @s remove killed_stray
tag @s remove killed_spider
tag @s remove killed_vex
tag @s remove killed_vindicator
tag @s remove killed_witch
tag @s remove killed_wither_skeleton
tag @s remove killed_wither
tag @s remove killed_zombie_pigman
tag @s remove killed_zombie_villager
tag @s remove killed_zombie

scoreboard players set @s phantomAtk 0

tag @s remove biome_basalt_deltas
tag @s remove biome_crimson_forest
tag @s remove biome_nether_wastes
tag @s remove biome_soulsand_valle
tag @s remove biome_warped_forest

tellraw @s {"rawtext":[{"translate":"chat.advancement.revoke.all.section","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.adventure.root.title"}]}}]}