tag @s remove adv69
tag @s remove adv70
tag @s remove adv71
tag @s remove adv72
tag @s remove adv73
tag @s remove adv74
tag @s remove adv75
tag @s remove adv76
tag @s remove adv77
tag @s remove adv78
tag @s remove adv79
tag @s remove adv80
tag @s remove adv86
tag @s remove adv87
tag @s remove adv88
tag @s remove adv89
tag @s remove adv90
tag @s remove adv91

tag @s remove consumed_apple
tag @s remove consumed_baked_potato
tag @s remove consumed_beetroot
tag @s remove consumed_beetroot_soup
tag @s remove consumed_bread
tag @s remove consumed_carrot
tag @s remove consumed_chorus_fruit
tag @s remove consumed_cooked_chicken
tag @s remove consumed_cooked_cod
tag @s remove consumed_cooked_mutton
tag @s remove consumed_cooked_porkchop
tag @s remove consumed_cooked_rabbit
tag @s remove consumed_cooked_salmon
tag @s remove consumed_cookie
tag @s remove consumed_dried_kelp
tag @s remove consumed_enchanted_golden_apple
tag @s remove consumed_golden_apple
tag @s remove consumed_golden_carrot
tag @s remove consumed_honey_bottle
tag @s remove consumed_melon_slice
tag @s remove consumed_mushroom_stew
tag @s remove consumed_poisonous_potato
tag @s remove consumed_potato
tag @s remove consumed_pufferfish
tag @s remove consumed_pumpkin_pie
tag @s remove consumed_rabbit_stew
tag @s remove consumed_raw_beef
tag @s remove consumed_raw_chicken
tag @s remove consumed_raw_cod
tag @s remove consumed_raw_mutton
tag @s remove consumed_raw_porkchop
tag @s remove consumed_raw_rabbit
tag @s remove consumed_raw_salmon
tag @s remove consumed_rotten_flesh
tag @s remove consumed_spider_eye
tag @s remove consumed_steak
tag @s remove consumed_suspicious_stew
tag @s remove consumed_sweet_berries
tag @s remove consumed_tropical_fish

tag @s remove tamed_cat_white
tag @s remove tamed_cat_tuxedo
tag @s remove tamed_cat_red
tag @s remove tamed_cat_siamese
tag @s remove tamed_cat_british
tag @s remove tamed_cat_calico
tag @s remove tamed_cat_persian
tag @s remove tamed_cat_ragdoll
tag @s remove tamed_cat_tabby
tag @s remove tamed_cat_black
tag @s remove tamed_cat_jellie

tag @s remove tamed_donkey
tag @s remove tamed_horse
tag @s remove tamed_llama
tag @s remove tamed_mule
tag @s remove tamed_ocelot
tag @s remove tamed_parrot
tag @s remove tamed_wolf

tellraw @s {"rawtext":[{"translate":"chat.advancement.revoke.all.section","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.husbandry.root.title"}]}}]}