tellraw @s[tag="adv79"] {"rawtext":[{"translate":"chat.advancement.revoke.success","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.husbandry.balanced_diet.title"}]}}]}
tellraw @s[tag=!"adv79"] {"rawtext":[{"text":"§c"},{"translate":"chat.advancement.revoke.fail","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.husbandry.balanced_diet.title"}]}}]}

tag @s remove consumed_apple
tag @s remove consumed_baked_potato
tag @s remove consumed_beetroot
tag @s remove consumed_beetroot_soup
tag @s remove consumed_bread
tag @s remove consumed_carrot
tag @s remove consumed_chorus_fruit
tag @s remove consumed_cooked_chicken
tag @s remove consumed_cooked_cod
tag @s remove consumed_cooked_mutton
tag @s remove consumed_cooked_porkchop
tag @s remove consumed_cooked_rabbit
tag @s remove consumed_cooked_salmon
tag @s remove consumed_cookie
tag @s remove consumed_dried_kelp
tag @s remove consumed_enchanted_golden_apple
tag @s remove consumed_golden_apple
tag @s remove consumed_golden_carrot
tag @s remove consumed_honey_bottle
tag @s remove consumed_melon_slice
tag @s remove consumed_mushroom_stew
tag @s remove consumed_poisonous_potato
tag @s remove consumed_potato
tag @s remove consumed_pufferfish
tag @s remove consumed_pumpkin_pie
tag @s remove consumed_rabbit_stew
tag @s remove consumed_raw_beef
tag @s remove consumed_raw_chicken
tag @s remove consumed_raw_cod
tag @s remove consumed_raw_mutton
tag @s remove consumed_raw_porkchop
tag @s remove consumed_raw_rabbit
tag @s remove consumed_raw_salmon
tag @s remove consumed_rotten_flesh
tag @s remove consumed_spider_eye
tag @s remove consumed_steak
tag @s remove consumed_suspicious_stew
tag @s remove consumed_sweet_berries
tag @s remove consumed_tropical_fish
tag @s remove adv79