tellraw @s[tag="adv65"] {"rawtext":[{"translate":"chat.achievement.take.success","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.adventure.adventuring_time.title"}]}}]}
tellraw @s[tag=!"adv65"] {"rawtext":[{"text":"§c"},{"translate":"chat.achievement.take.fail","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.adventure.adventuring_time.title"}]}}]}

tag @s remove biome_bamboo_jungle
tag @s remove biome_bamboo_jungle_hills
tag @s remove biome_beach
tag @s remove biome_birch_forest
tag @s remove biome_birch_forest_hills
tag @s remove biome_birch_forest_hills_mutated
tag @s remove biome_birch_forest_mutated
tag @s remove biome_cold_beach
tag @s remove biome_cold_ocean
tag @s remove biome_cold_taiga
tag @s remove biome_cold_taiga_hills
tag @s remove biome_cold_taiga_mutated
tag @s remove biome_deep_cold_ocean
tag @s remove biome_deep_frozen_ocean
tag @s remove biome_deep_lukewarm_ocean
tag @s remove biome_deep_ocean
tag @s remove biome_deep_warm_ocean
tag @s remove biome_desert
tag @s remove biome_desert_hills
tag @s remove biome_desert_mutated
tag @s remove biome_extreme_hills
tag @s remove biome_extreme_hills_edge
tag @s remove biome_extreme_hills_forest
tag @s remove biome_extreme_hills_mutated
tag @s remove biome_extreme_hills_mutated_forest
tag @s remove biome_flower_forest
tag @s remove biome_forest
tag @s remove biome_forest_hills
tag @s remove biome_frozen_ocean
tag @s remove biome_frozen_river
tag @s remove biome_ice_mountains
tag @s remove biome_ice_plains
tag @s remove biome_ice_plains_spikes
tag @s remove biome_jungle
tag @s remove biome_jungle_edge
tag @s remove biome_jungle_edge_mutated
tag @s remove biome_jungle_hills
tag @s remove biome_jungle_mutated
tag @s remove biome_lukewarm_ocean
tag @s remove biome_mega_spruce_taiga
tag @s remove biome_mega_spruce_taiga_hills
tag @s remove biome_mega_taiga
tag @s remove biome_mega_taiga_hills
tag @s remove biome_mesa
tag @s remove biome_mesa_bryce
tag @s remove biome_mesa_plateau
tag @s remove biome_mesa_plateau_mutated
tag @s remove biome_mesa_plateau_stone
tag @s remove biome_mesa_plateau_stone_mutated
tag @s remove biome_mushroom_island
tag @s remove biome_mushroom_island_shore
tag @s remove biome_ocean
tag @s remove biome_plains
tag @s remove biome_river
tag @s remove biome_roofed_forest
tag @s remove biome_roofed_forest_mutated
tag @s remove biome_savanna
tag @s remove biome_savanna_mutated
tag @s remove biome_savanna_plateau
tag @s remove biome_savanna_plateau_mutated
tag @s remove biome_stone_beach
tag @s remove biome_swamp
tag @s remove biome_swamp_mutated
tag @s remove biome_taiga
tag @s remove biome_taiga_hills
tag @s remove biome_taiga_mutated
tag @s remove biome_warm_ocean
tag @s remove adv65