tag @s remove adv1
tag @s remove adv2
tag @s remove adv3
tag @s remove adv4
tag @s remove adv5
tag @s remove adv6
tag @s remove adv7
tag @s remove adv8
tag @s remove adv9
tag @s remove adv10
tag @s remove adv11
tag @s remove adv12
tag @s remove adv13
tag @s remove adv14
tag @s remove adv15
tag @s remove adv16
tag @s remove adv17
tag @s remove adv18
tag @s remove adv19
tag @s remove adv20
tag @s remove adv21
tag @s remove adv22
tag @s remove adv23
tag @s remove adv24
tag @s remove adv25
tag @s remove adv26
tag @s remove adv27
tag @s remove adv28
tag @s remove adv29
tag @s remove adv30
tag @s remove adv31
tag @s remove adv32
tag @s remove adv33
tag @s remove adv34
tag @s remove adv35
tag @s remove adv36
tag @s remove adv37
tag @s remove adv38
tag @s remove adv39
tag @s remove adv40
tag @s remove adv41
tag @s remove adv42
tag @s remove adv43
tag @s remove adv44
tag @s remove adv45
tag @s remove adv46
tag @s remove adv47
tag @s remove adv48
tag @s remove adv49
tag @s remove adv50
tag @s remove adv51
tag @s remove adv52
tag @s remove adv53
tag @s remove adv54
tag @s remove adv55
tag @s remove adv56
tag @s remove adv57
tag @s remove adv58
tag @s remove adv59
tag @s remove adv60
tag @s remove adv61
tag @s remove adv62
tag @s remove adv63
tag @s remove adv64
tag @s remove adv65
tag @s remove adv66
tag @s remove adv67
tag @s remove adv68
tag @s remove adv69
tag @s remove adv70
tag @s remove adv71
tag @s remove adv72
tag @s remove adv73
tag @s remove adv74
tag @s remove adv75
tag @s remove adv76
tag @s remove adv77
tag @s remove adv78
tag @s remove adv79
tag @s remove adv80
tag @s remove adv81
tag @s remove adv82
tag @s remove adv83
tag @s remove adv84
tag @s remove adv85
tag @s remove adv86
tag @s remove adv87
tag @s remove adv88
tag @s remove adv89
tag @s remove adv90
tag @s remove adv91
tag @s remove warpTick
tag @s remove warpTick1
tag @s remove warpTick2

scoreboard players set @s uniqueAtk 0

tag @s remove biome_bamboo_jungle
tag @s remove biome_bamboo_jungle_hills
tag @s remove biome_beach
tag @s remove biome_birch_forest
tag @s remove biome_birch_forest_hills
tag @s remove biome_birch_forest_hills_mutated
tag @s remove biome_birch_forest_mutated
tag @s remove biome_cold_beach
tag @s remove biome_cold_ocean
tag @s remove biome_cold_taiga
tag @s remove biome_cold_taiga_hills
tag @s remove biome_cold_taiga_mutated
tag @s remove biome_deep_cold_ocean
tag @s remove biome_deep_frozen_ocean
tag @s remove biome_deep_lukewarm_ocean
tag @s remove biome_deep_ocean
tag @s remove biome_deep_warm_ocean
tag @s remove biome_desert
tag @s remove biome_desert_hills
tag @s remove biome_desert_mutated
tag @s remove biome_extreme_hills
tag @s remove biome_extreme_hills_edge
tag @s remove biome_extreme_hills_forest
tag @s remove biome_extreme_hills_mutated
tag @s remove biome_extreme_hills_mutated_forest
tag @s remove biome_flower_forest
tag @s remove biome_forest
tag @s remove biome_forest_hills
tag @s remove biome_frozen_ocean
tag @s remove biome_frozen_river
tag @s remove biome_ice_mountains
tag @s remove biome_ice_plains
tag @s remove biome_ice_plains_spikes
tag @s remove biome_jungle
tag @s remove biome_jungle_edge
tag @s remove biome_jungle_edge_mutated
tag @s remove biome_jungle_hills
tag @s remove biome_jungle_mutated
tag @s remove biome_lukewarm_ocean
tag @s remove biome_mega_spruce_taiga
tag @s remove biome_mega_spruce_taiga_hills
tag @s remove biome_mega_taiga
tag @s remove biome_mega_taiga_hills
tag @s remove biome_mesa
tag @s remove biome_mesa_bryce
tag @s remove biome_mesa_plateau
tag @s remove biome_mesa_plateau_mutated
tag @s remove biome_mesa_plateau_stone
tag @s remove biome_mesa_plateau_stone_mutated
tag @s remove biome_mushroom_island
tag @s remove biome_mushroom_island_shore
tag @s remove biome_ocean
tag @s remove biome_plains
tag @s remove biome_river
tag @s remove biome_roofed_forest
tag @s remove biome_roofed_forest_mutated
tag @s remove biome_savanna
tag @s remove biome_savanna_mutated
tag @s remove biome_savanna_plateau
tag @s remove biome_savanna_plateau_mutated
tag @s remove biome_stone_beach
tag @s remove biome_swamp
tag @s remove biome_swamp_mutated
tag @s remove biome_taiga
tag @s remove biome_taiga_hills
tag @s remove biome_taiga_mutated
tag @s remove biome_warm_ocean

tag @s remove killed_blaze
tag @s remove killed_cave_spider
tag @s remove killed_creeper
tag @s remove killed_drowned
tag @s remove killed_elder_guardian
tag @s remove killed_ender_dragon
tag @s remove killed_enderman
tag @s remove killed_endermite
tag @s remove killed_evocation_illager
tag @s remove killed_ghast
tag @s remove killed_guardian
tag @s remove killed_husk
tag @s remove killed_magma_cube
tag @s remove killed_phantom
tag @s remove killed_piglin
tag @s remove killed_piglin_brute
tag @s remove killed_pillager
tag @s remove killed_ravager
tag @s remove killed_shulker
tag @s remove killed_silverfish
tag @s remove killed_skeleton
tag @s remove killed_slime
tag @s remove killed_stray
tag @s remove killed_spider
tag @s remove killed_vex
tag @s remove killed_vindicator
tag @s remove killed_witch
tag @s remove killed_wither_skeleton
tag @s remove killed_wither
tag @s remove killed_zombie_pigman
tag @s remove killed_zombie_villager
tag @s remove killed_zombie

scoreboard players set @s phantomAtk 0

tag @s remove consumed_apple
tag @s remove consumed_baked_potato
tag @s remove consumed_beetroot
tag @s remove consumed_beetroot_soup
tag @s remove consumed_bread
tag @s remove consumed_carrot
tag @s remove consumed_chorus_fruit
tag @s remove consumed_cooked_chicken
tag @s remove consumed_cooked_cod
tag @s remove consumed_cooked_mutton
tag @s remove consumed_cooked_porkchop
tag @s remove consumed_cooked_rabbit
tag @s remove consumed_cooked_salmon
tag @s remove consumed_cookie
tag @s remove consumed_dried_kelp
tag @s remove consumed_enchanted_golden_apple
tag @s remove consumed_golden_apple
tag @s remove consumed_golden_carrot
tag @s remove consumed_honey_bottle
tag @s remove consumed_melon_slice
tag @s remove consumed_mushroom_stew
tag @s remove consumed_poisonous_potato
tag @s remove consumed_potato
tag @s remove consumed_pufferfish
tag @s remove consumed_pumpkin_pie
tag @s remove consumed_rabbit_stew
tag @s remove consumed_raw_beef
tag @s remove consumed_raw_chicken
tag @s remove consumed_raw_cod
tag @s remove consumed_raw_mutton
tag @s remove consumed_raw_porkchop
tag @s remove consumed_raw_rabbit
tag @s remove consumed_raw_salmon
tag @s remove consumed_rotten_flesh
tag @s remove consumed_spider_eye
tag @s remove consumed_steak
tag @s remove consumed_suspicious_stew
tag @s remove consumed_sweet_berries
tag @s remove consumed_tropical_fish

tag @s remove tamed_cat_white
tag @s remove tamed_cat_tuxedo
tag @s remove tamed_cat_red
tag @s remove tamed_cat_siamese
tag @s remove tamed_cat_british
tag @s remove tamed_cat_calico
tag @s remove tamed_cat_persian
tag @s remove tamed_cat_ragdoll
tag @s remove tamed_cat_tabby
tag @s remove tamed_cat_black
tag @s remove tamed_cat_jellie

tag @s remove tamed_donkey
tag @s remove tamed_horse
tag @s remove tamed_llama
tag @s remove tamed_mule
tag @s remove tamed_ocelot
tag @s remove tamed_parrot
tag @s remove tamed_wolf

tag @s remove biome_basalt_deltas
tag @s remove biome_crimson_forest
tag @s remove biome_nether_wastes
tag @s remove biome_soulsand_valle
tag @s remove biome_warped_forest

tellraw @s {"rawtext":[{"translate":"chat.advancement.revoke.all.everything","with":{"rawtext":[{"selector":"@s"}]}}]}